version: '3.4'

services:
  taxajuros:
    image: taxajuros
    build:
      "./taxajuros"
    container_name: taxajuros-container
    ports:
      - 4444:80
    networks: 
      - desafio-network  
  calculajuros:
    image: calculajuros
    build:
      "./calculajuros"
    container_name: calculajuros-container
    ports:
      - 5555:80
    networks: 
      - desafio-network
networks:
  desafio-network:
    driver: "bridge"